/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainPackage_Main */

#ifndef _Included_mainPackage_Main
#define _Included_mainPackage_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mainPackage_Main
 * Method:    nativeParallelMatrixMultiplikation
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_mainPackage_Main_nativeParallelMatrixMultiplikation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     mainPackage_Main
 * Method:    nativeSequentialMatrixMultiplikation
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_mainPackage_Main_nativeSequentialMatrixMultiplikation
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
